import Head from "next/head";
import Link from "next/link";
import {useEffect, useState} from "react";

export default function Home() {
    const grid = new Array(144).fill(true);
    const [snake, setSnake] = useState({
        length: 1,
        position: {
            x: 0,
            y: 0,
        },
        direction: "right",
    });
    const updateSnake = () => {
        // This will run every second!
        setSnake((prev) => {
            const {x, y} = prev.position;
            switch (prev.direction) {
                case "right":
                    return {
                        ...prev,
                        position: {
                            x: x % 12 === 11 ? 0 : x + 1,
                            y,
                        },
                    };
                case "left":
                    return {
                        ...prev,
                        position: {
                            x: x - 1,
                            y,
                        },
                    };
                case "up":
                    return {
                        ...prev,
                        position: {
                            x,
                            y: y % 12 === 0 ? 11 : y - 1,
                        },
                    };
                case "down":
                    return {
                        ...prev,
                        position: {
                            x,
                            y: y % 12 === 11 ? 0 : y + 1,
                        },
                    };
                default:
                    return prev;
            }
        });
    }

    // key presses
    const onKeyDown = (e: any) => {
        switch (e.key) {
            case "ArrowUp":
                setSnake((prev) => ({
                    ...prev,
                    direction: "up",
                }));
                break;
            case "ArrowDown":
                setSnake((prev) => ({
                    ...prev,
                    direction: "down",
                }));
                break;
            case "ArrowLeft":
                setSnake((prev) => ({
                    ...prev,
                    direction: "left",
                }));
                break;
            case "ArrowRight":
                setSnake((prev) => ({
                    ...prev,
                    direction: "right",
                }));
                break;
            default:
                break;
        }
    }

    useEffect(() => {
        const interval = setInterval(() => {
            updateSnake();
        }, 1000);
        window.addEventListener("keydown", onKeyDown);

        return () => {
            clearInterval(interval);
            window.removeEventListener("keydown", onKeyDown);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main
                className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

                <div className="grid grid-cols-12 gap-1">
                    {
                        grid.map((_, index) => {
                            const x = index % 12;
                            const y = Math.floor(index / 12);
                            let isHere = (snake.position.x === x && snake.position.y === y) ? true : false;
                            return (
                                <div
                                    className={`w-10 h-10 rounded-sm
                                    ${isHere ? 'bg-black' : 'bg-white'}`}
                                    key={index}
                                >
                                    {x} {y}
                                </div>
                            )
                        })
                    }
                </div>

            </main>
        </>
    );
}
